# -*- coding: utf-8 -*-
from marriage_engine.look import ABOUT
G6 = (
    {"id": "seedcuke", "name": "Саженец огурца", "name1": "mrgseedcuke", "emoji": "🌱🥒", "price": 15, "care": 0, "effect": "seed", "buy": "Купить саженец", "use": "На ферму", "touch": "Саженец сажают на ферме.", "line": ABOUT["seedcuke"], "craft": "Ферма: 30 минут и 3 полива. Урожай — огурец.", "on": True, "growMin": 30, "waters": 3},
    {"id": "seedtom", "name": "Саженец помидора", "name1": "mrgseedtom", "emoji": "🌱🍅", "price": 15, "care": 0, "effect": "seed", "buy": "Купить саженец", "use": "На ферму", "touch": "Саженец сажают на ферме.", "line": ABOUT["seedtom"], "craft": "Ферма: 30 минут и 3 полива. Урожай — помидор.", "on": True, "growMin": 30, "waters": 3},
    {"id": "seedcab", "name": "Саженец капусты", "name1": "mrgseedcab", "emoji": "🌱🥬", "price": 15, "care": 0, "effect": "seed", "buy": "Купить саженец", "use": "На ферму", "touch": "Саженец сажают на ферме.", "line": ABOUT["seedcab"], "craft": "Ферма: 30 минут и 3 полива. Урожай — капуста.", "on": True, "growMin": 30, "waters": 3},
    {"id": "cuke", "name": "Огурец", "name1": "mrgcuke", "emoji": "🥒", "price": 0, "care": 0, "effect": "pantry", "buy": "Купить", "use": "В крафт", "touch": "Огурец ждёт тарелку.", "line": ABOUT["cuke"], "craft": "Крафт: сок с помидором, салат с помидором и капустой.", "on": False},
    {"id": "tom", "name": "Помидор", "name1": "mrgtom", "emoji": "🍅", "price": 0, "care": 0, "effect": "pantry", "buy": "Купить", "use": "В крафт", "touch": "Помидор ждёт тарелку.", "line": ABOUT["tom"], "craft": "Крафт: сок с огурцом, суп с капустой, салат со всеми тремя.", "on": False},
    {"id": "cab", "name": "Капуста", "name1": "mrgcab", "emoji": "🥬", "price": 0, "care": 0, "effect": "pantry", "buy": "Купить", "use": "В крафт", "touch": "Капуста ждёт тарелку.", "line": ABOUT["cab"], "craft": "Крафт: суп с помидором, салат с огурцом и помидором.", "on": False},
    {"id": "juice", "name": "Сок вдвоём", "name1": "mrgjuice", "emoji": "🥤", "price": 0, "care": 8, "effect": "both", "buy": "Купить", "use": "Выпить", "touch": "Обоим по +8.", "line": ABOUT["juice"], "craft": "Огурец + помидор.", "on": False},
    {"id": "soup", "name": "Суп вдвоём", "name1": "mrgsoup", "emoji": "🍲", "price": 0, "care": 12, "effect": "both", "buy": "Купить", "use": "Съесть", "touch": "Обоим по +12.", "line": ABOUT["soup"], "craft": "Капуста + помидор.", "on": False},
    {"id": "salad", "name": "Салат вдвоём", "name1": "mrgsalad", "emoji": "🥗", "price": 0, "care": 15, "effect": "both", "buy": "Купить", "use": "Съесть", "touch": "Обоим по +15. Ужин вместе.", "line": ABOUT["salad"], "craft": "Огурец + помидор + капуста.", "on": False},
)
