# -*- coding: utf-8 -*-
"""AUTO-GENERATED — do not edit by hand.

Источник: сканер всех @callback_query в репозитории.
Пересобрать: python -m bot.runtime._gen_callback_registry
"""
from __future__ import annotations

from typing import Dict, List, Tuple

# modules with @callback_query: 66
CALLBACK_MODULES: Tuple[str, ...] = (
    'bot.admins.ban',
    'bot.admins.kick',
    'bot.admins.mute',
    'bot.admins.warn',
    'bot.buisnesses.clan_filter',
    'bot.design.induel',
    'bot.design.inlinekn',
    'bot.design.inlinememory',
    'bot.design.inlinetictac2',
    'bot.design.inlinetictactoe',
    'bot.design.inmine',
    'bot.design.inorel',
    'bot.design.schahinline',
    'bot.design.sub',
    'bot.funcs.BlackGack',
    'bot.funcs.CuteCoin',
    'bot.funcs.Gelicopter',
    'bot.funcs.Roulett',
    'bot.funcs.Shep',
    'bot.funcs.Shine',
    'bot.funcs.balance',
    'bot.funcs.bingo',
    'bot.funcs.dzrebi',
    'bot.funcs.garden',
    'bot.funcs.help',
    'bot.funcs.history',
    'bot.funcs.knb',
    'bot.funcs.kosti',
    'bot.funcs.marriage',
    'bot.funcs.onboarding',
    'bot.funcs.orel',
    'bot.funcs.profile',
    'bot.funcs.promo',
    'bot.funcs.reklama',
    'bot.funcs.ruletka',
    'bot.funcs.shepinline',
    'bot.funcs.shop',
    'bot.funcs.shophouse',
    'bot.funcs.shopvir',
    'bot.funcs.tic_tac_toe',
    'bot.funcs.top',
    'bot.games.Fortuna',
    'bot.games.balls',
    'bot.games.bombs',
    'bot.games.bullet',
    'bot.games.crash',
    'bot.games.game',
    'bot.games.gild',
    'bot.games.memory',
    'bot.games.mines',
    'bot.games.plate',
    'bot.games.provoda',
    'bot.games.risk',
    'bot.games.scah',
    'bot.games.tank',
    'bot.games.word',
    'bot.handlers.chatbalance',
    'bot.handlers.editprofile',
    'bot.handlers.handlers_btns',
    'bot.handlers.useitems',
    'bot.tggames.basket',
    'bot.tggames.bowling',
    'bot.tggames.darts',
    'bot.tggames.kube',
    'bot.tggames.slots',
    'bot.tggames.soccer',
)

# prefix -> (module, handler): 382
PREFIX_HANDLERS: Dict[str, Tuple[str, str]] = {
    'ajdfiasjoaskdokasdqwqkpфыафывйц': ('main', 'send_styles'),
    'callbroulletanswermultiplier': ('bot.games.Fortuna', 'fortuna_multiplier_info'),
    'next_pagemoneyhistorygame_': ('bot.funcs.history', 'process_callback_button'),
    'prev_pagemoneyhistorygame_': ('bot.funcs.history', 'process_callback_button'),
    '2flagconfirm_flag_removal': ('bot.funcs.balance', 'process_callback'),
    'balance312512512651action': ('bot.funcs.balance', 'send_styles'),
    'inlinesurrendertictactoe:': ('bot.design.inlinetictac2', 'inline_tic_tac_surrender_callback'),
    'refwithdrawalrefprofile1': ('main', 'process_callback_kb1btn1'),
    'smarriageend_request_pm_': ('bot.funcs.marriage', 'my_marriage_info'),
    'ajdfiasjoaskdokasdqwqkp': ('main', 'send_styles'),
    'confirm_gelicoptersell_': ('bot.funcs.Gelicopter', 'confirm_sell_callback'),
    'qst:broken_details_ref:': ('main', 'qst_broken_details_ref'),
    'rahdachaclandistribute_': ('bot.buisnesses.clan_filter', 'handle_clan_distribution_distribute'),
    'confirm_clan_creation:': ('bot.buisnesses.clan_filter', 'handle_clan_creation_callback'),
    'giftconfirmwithdrawal_': ('main', 'giftconfirmwithdrawal_callback'),
    'giftgift_send_request_': ('main', 'send_request_callback_friend'),
    'giftmanualunavailable:': ('main', 'gift_manual_unavailable_callback'),
    'next_pagemoneyhistory_': ('main', 'process_callback_button'),
    'prev_pagemoneyhistory_': ('main', 'process_callback_button'),
    'group_balance_details': ('bot.handlers.chatbalance', 'show_balance_details'),
    'marriageclosemessage_': ('bot.funcs.marriage', 'send_request_pm'),
    'confirm3412_purchase': ('bot.funcs.CuteCoin', 'process_callback'),
    'gift_toggle_upgrade|': ('main', 'toggle_upgrade_callback'),
    'inline_view_message_': ('bot.design.inlinekn', 'view_message'),
    'inlinemovetictactoe:': ('bot.design.inlinetictac2', 'inline_tic_tac_make_move_callback'),
    'promo_confirm123xyz|': ('bot.funcs.promo', 'confirm_promo'),
    'shahsurrenderinline:': ('bot.design.schahinline', 'surrender_callback'),
    'cancel3412_purchase': ('bot.funcs.CuteCoin', 'process_callback'),
    'confirm_gelicopter_': ('bot.funcs.Gelicopter', 'confirm_buy_callback'),
    'giveaccept_transfer': ('bot.design.inlinekn', 'accept_transfer_handler'),
    'oinlinememory_open:': ('bot.design.inlinememory', 'inline_memory_memory_open111'),
    'qst:broken_details:': ('main', 'qst_broken_details'),
    'rahdachaclancancel_': ('bot.buisnesses.clan_filter', 'handle_clan_distribution_cancel'),
    'sinlainmemorystart:': ('bot.design.inlinememory', 'inline_memory_start_game_callback'),
    'surrendertictactoe:': ('bot.funcs.tic_tac_toe', 'surrender_callback'),
    'waiting9close_bonus': ('main', 'waiting_close_bonus_callback'),
    'clan_accept_entry_': ('bot.buisnesses.clan_filter', 'process_callback'),
    'clan_reject_entry_': ('bot.buisnesses.clan_filter', 'process_callback'),
    'confirm_promotion:': ('bot.buisnesses.clan_filter', 'promotion_callback_handler'),
    'confirmhouse_sell_': ('bot.funcs.shophouse', 'confirm_sell_callback'),
    'dddaccept_transfer': ('bot.design.inlinekn', 'accept_transfer_handler_ddd'),
    'filter_by_sorting_': ('bot.funcs.shop', 'apply_filter_handler'),
    'gift_send_request_': ('main', 'gift_send_request'),
    'podrobneebingohui_': ('bot.funcs.bingo', 'bingo_send_styles'),
    'podrobneekostihui_': ('bot.funcs.kosti', 'kosti_send_game_results'),
    'unique_start_game:': ('bot.design.schahinline', 'start_checkers_game_callback'),
    '2412bombsskukota_': ('bot.games.bombs', 'bombs_bombsskukota_game'),
    '3412helpstarthelp': ('main', 'callback_top'),
    '9help_editprofile': ('bot.funcs.help', 'qwehelp_editprofile'),
    'cancel_promotion:': ('bot.buisnesses.clan_filter', 'promotion_callback_handler'),
    'confirm_surrender': ('bot.buisnesses.clan_filter', 'process_confirm_surrender'),
    'confirmwithdrawal': ('main', 'confirm_withdrawal_callback'),
    'ddaccept_transfer': ('bot.design.inlinekn', 'accept_transfer_handler_dd'),
    'demotion_confirm_': ('bot.buisnesses.clan_filter', 'confirm_demotion'),
    'errorsoccermoney_': ('bot.tggames.soccer', 'errorsoccermoney_alert'),
    'inlinememoryjoin:': ('bot.design.inlinememory', 'inline_memory_join_memory_game'),
    'minfowaitingbonus': ('main', 'infowaitingbonus_handler'),
    'next_pagemarryxp_': ('bot.funcs.top', 'handle_marryxp_pagination'),
    'prev_pagemarryxp_': ('bot.funcs.top', 'handle_marryxp_pagination'),
    'promotion_cancel_': ('bot.buisnesses.clan_filter', 'cancel_promotion'),
    'qst:gc_free_info:': ('main', 'gc_free_info_callback'),
    'qst:gctake_force:': ('main', 'gc_take_force_callback'),
    'translationsgames': ('bot.funcs.history', 'process_callback'),
    'unique_join_game:': ('bot.design.schahinline', 'join_checkers_game_callback'),
    'userwinamountstop': ('bot.funcs.top', 'callasfasfawqfqwback_top'),
    '2tart_set_board:': ('bot.design.inlinetictac2', 'inline_tic_tac_set_board_start_size'),
    '9help_deletehelp': ('main', 'callback_top'),
    'bal_sleep_games:': ('bot.funcs.balance', 'cb_bal_sleep_games'),
    'demotion_cancel_': ('bot.buisnesses.clan_filter', 'cancel_demotion'),
    'donaters34123412': ('bot.funcs.top', 'callbiahsdofhasodfhoasack_top'),
    'errorslotspedro_': ('bot.tggames.slots', 'slots_chatbank_alert'),
    'gift_reset_desc|': ('main', 'gift_reset_desc_callback'),
    'help_deletestate': ('bot.funcs.top', 'calljiqwjicqjqback_top'),
    'help_editprofile': ('bot.funcs.help', 'asundifcallback_main'),
    'infowaitingbonus': ('main', 'infowaitingbonus_handler'),
    'mineclickinmine:': ('bot.design.inmine', 'inline_mine_mine_click_callback'),
    'minestartinmine:': ('bot.design.inmine', 'inline_mine_start_game_callback'),
    'outrefunddelete_': ('main', 'delete_messagedw1d1wd1dw1'),
    'preparationsend_': ('main', 'send_request_callback'),
    'sell_gelicopter_': ('bot.funcs.Gelicopter', 'sell_gelicopter_callback'),
    'shootroulinduel_': ('bot.design.induel', 'induel_Roullet_process_shoot'),
    'speedwithdrawal2': ('b_Eden.Garden_of_Eden', 'speed_withdrawal_callback'),
    'start_tictactoe:': ('bot.design.inlinetictac2', 'inline_tic_tac_start_game_callback'),
    'startorelinline:': ('bot.design.inorel', 'inline_start_game_callback'),
    'startroulinduel_': ('bot.design.induel', 'induel_Roullet_process_start'),
    'surrender_battle': ('bot.buisnesses.clan_filter', 'process_surrender'),
    'user_next1_page_': ('bot.funcs.Gelicopter', 'process_page_callback'),
    'user_prev1_page_': ('bot.funcs.Gelicopter', 'process_page_callback'),
    'view_gelicopter_': ('bot.funcs.Gelicopter', 'view_gelicopter'),
    'wordswin_amount_': ('main', 'wordswin_amount'),
    '1tmemory_create': ('bot.design.inlinememory', 'inline_memory_create_game_callback'),
    'balancegrouptop': ('bot.funcs.top', 'calsadqwdqwqdqwcqlback_top'),
    'bonusstartbonus': ('main', 'callback_top'),
    'buy_gelicopter_': ('bot.funcs.Gelicopter', 'process_callback'),
    'buy_with_coupon': ('bot.funcs.shop', 'handle_confirm_purchase'),
    'checkcucumbers_': ('bot.funcs.garden', 'handle_check'),
    'checkers_create': ('bot.design.schahinline', 'create_checkers_game_callback'),
    'confirm_rename:': ('bot.buisnesses.clan_filter', 'process_confirm_rename'),
    'giftmenudelete:': ('bot.funcs.balance', 'gift_menu_delete_gift_callback'),
    'help_deletehelp': ('bot.funcs.help', 'calasdspaldasqwsqflback_top'),
    'joinorelinline:': ('bot.design.inorel', 'inline_join_game_callback'),
    'joinroulinduel_': ('bot.design.induel', 'induel_Roullet_process_join'),
    'minejoininmine:': ('bot.design.inmine', 'inline_mine_join_game_callback'),
    'motion_confirm_': ('bot.buisnesses.clan_filter', 'confirm_promotion'),
    'next_pagemarry_': ('bot.funcs.top', 'handle_marry_pagination'),
    'plate_paid_stub': ('bot.games.plate', 'plate_paid_stub'),
    'plate_withdraw_': ('bot.games.plate', 'plate_process_withdraw'),
    'prev_pagemarry_': ('bot.funcs.top', 'handle_marry_pagination'),
    'qst:group_info:': ('main', 'qst_group_info'),
    'repost_btn_send': ('bot.handlers.handlers_btns', 'callback_main'),
    'risk_paid_stub_': ('bot.games.risk', 'risk_paid_stub'),
    'rollorelinline:': ('bot.design.inorel', 'inline_roll_callback'),
    'speedwithdrawal': ('main', 'speed_withdrawal_callback'),
    'starttictactoe:': ('bot.funcs.tic_tac_toe', 'start_game_callback'),
    'tart_set_board:': ('bot.funcs.tic_tac_toe', 'set_board_start_size'),
    'toggle_private:': ('bot.buisnesses.clan_filter', 'process_toggle_private'),
    'user_next_page_': ('bot.funcs.shophouse', 'process_page_callback'),
    'user_prev_page_': ('bot.funcs.shophouse', 'process_page_callback'),
    '123refprofile1': ('bot.funcs.reklama', 'process_callback_kb1btn1'),
    '1tic_tac_join:': ('bot.design.inlinetictac2', 'inline_tic_tac_join_game_callback'),
    '9back_to_menu1': ('main', 'handle_back_to_menu'),
    'ach_grant_off:': ('main', 'achievements_callbacks'),
    'back_to_stars_': ('main', 'back_to_stars_handler'),
    'back_to_x2_req': ('main', 'back_to_x2_requirements_handler'),
    'checkers_mode:': ('bot.design.schahinline', 'change_mode_callback'),
    'confirm_finish': ('bot.buisnesses.clan_filter', 'process_confirm_finish'),
    'confirm_house_': ('bot.funcs.shophouse', 'confirm_buy_callback'),
    'decline_action': ('bot.design.inlinekn', 'decline_action_handler'),
    'deletehelp0101': ('main', 'callback_top'),
    'giftmenureset:': ('bot.funcs.balance', 'gift_menu_reset_emoji_callback'),
    'jointictactoe:': ('bot.funcs.tic_tac_toe', 'tictactoe_join_game_callback'),
    'marrylovecoins': ('bot.funcs.top', 'callcqdqkiwqback_top'),
    'mouse_withdraw': ('bot.games.game', 'process_adm_menu'),
    'movetictactoe:': ('bot.funcs.tic_tac_toe', 'make_move_callback'),
    'plate_end_stub': ('bot.games.plate', 'plate_end_stub'),
    'plate_msg_stub': ('bot.games.plate', 'plate_msg_stub'),
    'qst:gc_broken:': ('main', 'gc_broken_callback'),
    'risk_msg_stub_': ('bot.games.risk', 'risk_msg_stub'),
    'risk_withdraw_': ('bot.games.risk', 'risk_process_withdraw'),
    'shahsurrender:': ('bot.games.scah', 'scah_surrender_callback'),
    'starthowtoplay': ('main', 'process_game_buttons'),
    'tank_paid_stub': ('bot.games.tank', 'tank_paid_stub'),
    'tank_withdraw_': ('bot.games.tank', 'tank_process_withdraw'),
    'tic_tac_create': ('bot.design.inlinetictac2', 'inline_tic_tac_create_game_callback'),
    '9help_btnfunk': ('bot.funcs.help', 'calybybybrvcrelback_main'),
    '9help_btnking': ('bot.funcs.help', 'callback_help_king_9'),
    'accept_action': ('bot.design.inlinekn', 'accept_action_handler'),
    'apply_change:': ('bot.buisnesses.clan_filter', 'process_apply_change'),
    'back_to_menu1': ('bot.funcs.profile', 'handle_back_to_menu'),
    'buy_s123tars:': ('main', 'handle_buy_stars'),
    'cancel_finish': ('bot.buisnesses.clan_filter', 'process_cancel_finish'),
    'checkcabbage_': ('bot.funcs.garden', 'handle_check'),
    'choose_stick:': ('bot.funcs.dzrebi', 'choose_stick_callback'),
    'confirm_sell_': ('bot.funcs.shopvir', 'confirm_sell_callback'),
    'craft_choose:': ('bot.funcs.shop', 'craft_choose_handler'),
    'donate_info2:': ('b_Eden.Garden_of_Eden', 'cb_donate_info'),
    'errorbowling_': ('bot.tggames.bowling', 'errorbowling_alert'),
    'finish_battle': ('bot.buisnesses.clan_filter', 'process_finish_battle'),
    'gift_confirm|': ('main', 'gift_confirm_callback'),
    'help_btnadmin': ('bot.funcs.help', 'admin_help_callback'),
    'helpstarthelp': ('main', 'callback_top'),
    'induel_create': ('bot.design.induel', 'induel_create_game_callback'),
    'inlinechange:': ('bot.design.schahinline', 'change_piece_callback'),
    'inlineselect:': ('bot.design.schahinline', 'select_piece_callback'),
    'inmine_create': ('bot.design.inmine', 'inline_mine_create_game_callback'),
    'inorel_create': ('bot.design.inorel', 'inline_create_game_callback'),
    'monthstate123': ('bot.funcs.top', 'cb_stats_month'),
    'plate_actual_': ('bot.games.plate', 'plate_process_game_buttons'),
    'qst:sub_page:': ('main', 'qst_sub_page'),
    'qst:sub_show:': ('main', 'qst_sub_show'),
    'qst:withdraw:': ('main', 'qst_withdraw_callback'),
    'rpschooseknb:': ('bot.design.inlinekn', 'inline_knb_choose_callback'),
    'send_request_': ('main', 'send_request_callback_self'),
    'show_ref_link': ('main', 'show_ref_link_cb'),
    'startruletka:': ('bot.funcs.ruletka', 'ruletka_start_game_callback'),
    'tank_msg_stub': ('bot.games.tank', 'tank_msg_stub'),
    'view_message_': ('bot.funcs.Shep', 'asdasdview_message'),
    'weclancancel_': ('bot.buisnesses.clan_filter', 'process_cancel_clan'),
    '9close_bonus': ('main', 'close_bonus_callback'),
    'apply_coupon': ('bot.funcs.shop', 'handle_apply_coupon'),
    'bulletstart:': ('bot.games.bullet', 'start_game_callback'),
    'checkbanana_': ('bot.funcs.garden', 'handle_check'),
    'checkcarrot_': ('bot.funcs.garden', 'handle_check'),
    'checkpotato_': ('bot.funcs.garden', 'handle_check'),
    'confirm_buy_': ('bot.funcs.shopvir', 'confirm_buy_callback'),
    'confirm_sell': ('bot.funcs.CuteCoin', 'confirm_sell'),
    'confirmdell:': ('bot.funcs.shop', 'confirm_action'),
    'donate_info:': ('main', 'cb_donate_info'),
    'errorbasket_': ('bot.tggames.basket', 'errorbasket_alert'),
    'filter_page_': ('bot.funcs.shop', 'paginate_handler'),
    'gameshistory': ('bot.funcs.history', 'process_callback'),
    'help_btnfunk': ('bot.funcs.help', 'calltewdxwback_main'),
    'help_btnking': ('bot.funcs.help', 'callback_help_king'),
    'help_store10': ('bot.funcs.help', 'cahfduascniamwwallback_top'),
    'help_store99': ('bot.funcs.help', 'calisackascvaslback_top'),
    'joinruletka:': ('bot.funcs.ruletka', 'ruletka_join_game_callback'),
    'kick:cancel:': ('bot.admins.kick', 'on_kick_pending_cancel'),
    'kow_purchase': ('bot.funcs.CuteCoin', 'process_callback'),
    'memory_open:': ('bot.games.memory', 'memory_open'),
    'memorystart:': ('bot.games.memory', 'memory_start_game_callback'),
    'michainlain:': ('bot.design.schahinline', 'draw_callback'),
    'monthnav123:': ('bot.funcs.top', 'cb_stats_month_nav'),
    'mute:cancel:': ('bot.admins.mute', 'mute_cancel_callback'),
    'mute:revoke:': ('bot.admins.mute', 'mute_revoke_callback'),
    'qst:gc_info:': ('main', 'gc_task_info_callback'),
    'qst:gc_page:': ('main', 'gc_page_callback'),
    'qst:gc_show:': ('main', 'gc_show_one_callback'),
    'qst:gcstart:': ('main', 'gc_start_callback'),
    'risk_actual_': ('bot.games.risk', 'risk_process_game_buttons'),
    'startdzrebi:': ('bot.funcs.dzrebi', 'start_dzrebi_callback'),
    'tank_actual_': ('bot.games.tank', 'tank_process_game_buttons'),
    'textglobhelp': ('bot.funcs.help', 'callback_tadfhadj9fwop'),
    'twogreet_cut': ('main', 'process_game_buttons'),
    'userloosetop': ('bot.funcs.top', 'casdasdqwqdqwallback_top'),
    'warn:cancel:': ('bot.admins.warn', 'on_warn_pending_cancel'),
    'warn:revoke:': ('bot.admins.warn', 'on_warn_revoke'),
    'weekstate123': ('bot.funcs.top', 'cb_stats_week'),
    'yearstate123': ('bot.funcs.top', 'cb_stats_year'),
    '3set_board:': ('bot.design.inlinetictac2', 'inline_tic_tac_set_board_size'),
    '9help_btn22': ('bot.funcs.help', 'callbaYTRWEQck_main'),
    'ban:cancel:': ('bot.admins.ban', 'on_ban_pending_cancel'),
    'ban:revoke:': ('bot.admins.ban', 'on_ban_revoke'),
    'bulletjoin:': ('bot.games.bullet', 'join_game_callback'),
    'checkapple_': ('bot.funcs.garden', 'handle_check'),
    'checkberry_': ('bot.funcs.garden', 'handle_check'),
    'checkmarix_': ('bot.funcs.garden', 'handle_check'),
    'checkmelon_': ('bot.funcs.garden', 'handle_check'),
    'conc_stars:': ('main', 'is_animated_emoji'),
    'donate_buy:': ('bot.design.inlinekn', 'donate_buy_callback'),
    'errordarts_': ('bot.tggames.darts', 'errordarts_alert'),
    'joindzrebi:': ('bot.funcs.dzrebi', 'join_game_callback'),
    'kostistart:': ('bot.funcs.kosti', 'kosti_start_game_callback'),
    'memoryjoin:': ('bot.games.memory', 'memory_join_game'),
    'next1_page_': ('bot.funcs.Gelicopter', 'process_page_callback'),
    'prev1_page_': ('bot.funcs.Gelicopter', 'process_page_callback'),
    'qeclanjoin_': ('bot.buisnesses.clan_filter', 'process_join_clan'),
    'refprofile1': ('bot.funcs.profile', 'process_callback_kb1btn1'),
    'repost_btn1': ('bot.handlers.handlers_btns', 'process_adm_menu'),
    'sell_house_': ('bot.funcs.shophouse', 'sell_car_callback'),
    'startbingo:': ('bot.funcs.bingo', 'bingo_start_game_callback'),
    'userwinstop': ('bot.funcs.top', 'callasdqiqjback_top'),
    'view_house_': ('bot.funcs.shophouse', 'view_house'),
    'weeknav123:': ('bot.funcs.top', 'cb_stats_week_nav'),
    'yearnav123:': ('bot.funcs.top', 'cb_stats_year_nav'),
    '9help_btn1': ('bot.funcs.help', 'callbadfssgfafdsack_main'),
    '9help_btn2': ('bot.funcs.help', 'callQWRQWRQback_main'),
    '9help_btn3': ('bot.funcs.help', 'callbacrvecek_main'),
    '9help_btn4': ('bot.funcs.help', 'caloakdaslpdlback_main'),
    '9help_btn5': ('bot.funcs.help', 'callback_aosdaslpdmain'),
    '9help_btn6': ('bot.funcs.help', 'callapsdlasdlback_main'),
    'bal_timer:': ('bot.funcs.balance', 'cb_balance_timer_info'),
    'btninsert_': ('main', 'buy_stars_handler'),
    'buy_house_': ('bot.funcs.shophouse', 'process_callback'),
    'checkcorn_': ('bot.funcs.garden', 'handle_check'),
    'chooseknb:': ('bot.funcs.knb', 'knb_choose_callback'),
    'clan_page_': ('bot.buisnesses.clan_filter', 'process_pagination'),
    'craftpage_': ('bot.handlers.useitems', 'process_pagination'),
    'daynav123:': ('bot.funcs.top', 'cb_stats_day_nav'),
    'errorkube_': ('bot.tggames.kube', 'errorkube_alert'),
    'gift_desc|': ('main', 'gift_desc_callback'),
    'gift_hide|': ('main', 'gift_hide_callback'),
    'gildclick:': ('bot.games.gild', 'board_click_callback'),
    'gildstart:': ('bot.games.gild', 'start_game_callback'),
    'help_btn22': ('bot.funcs.help', 'callback_erwqedsaCXZmain'),
    'inus_join_': ('bot.buisnesses.clan_filter', 'process_reject_join'),
    'joinbingo:': ('bot.funcs.bingo', 'bingo_join_game_callback'),
    'kostijoin:': ('bot.funcs.kosti', 'kosti_join_game_callback'),
    'kostiroll:': ('bot.funcs.kosti', 'kosti_roll_callback'),
    'kutenin123': ('bot.funcs.top', 'callasqsvevqwqqeback_top'),
    'mineclick:': ('bot.games.mines', 'mines_mine_click_callback'),
    'minestart:': ('bot.games.mines', 'mines_start_game_callback'),
    'money_lost': ('bot.handlers.handlers_btns', 'callback_top'),
    'next_page_': ('bot.funcs.Gelicopter', 'process_page_callback'),
    'ob_gstart:': ('bot.funcs.onboarding', 'ob_gstart'),
    'outdelete_': ('main', 'delete_messaasdqsqd1w1ge'),
    'prev_page_': ('bot.funcs.Gelicopter', 'process_page_callback'),
    'qst:check:': ('main', 'qst_sub_check'),
    'rollbingo:': ('bot.funcs.bingo', 'bingo_roll_callback'),
    'rps_create': ('bot.design.inlinekn', 'inline_knb_create_game_callback'),
    'set_board:': ('bot.funcs.tic_tac_toe', 'set_board_size'),
    'shootroul_': ('bot.funcs.Roulett', 'Roullet_process_shoot'),
    'speedconc_': ('main', 'speedconc_request_callback'),
    'start_rps:': ('bot.design.inlinekn', 'inline_knb_start_game_callback'),
    'startorel:': ('bot.funcs.orel', 'start_game_callback'),
    'startroul_': ('bot.funcs.Roulett', 'Roullet_process_start'),
    'style3412_': ('bot.funcs.profile', 'send_styles'),
    'user_page_': ('bot.buisnesses.clan_filter', 'process_pagination'),
    'btnstars_': ('main', 'btnstars_callback'),
    'ept_join_': ('bot.buisnesses.clan_filter', 'process_accept_join'),
    'gildjoin:': ('bot.games.gild', 'join_game_callback'),
    'greet_cut': ('main', 'greet_cut_handler'),
    'help_btn1': ('bot.funcs.help', 'callbadfsDFGGQack_main'),
    'help_btn2': ('bot.funcs.help', 'call12412512back_main'),
    'help_btn3': ('bot.funcs.help', 'call1dacadcaback_main'),
    'help_btn4': ('bot.funcs.help', 'callbacsqdqwdqk_main'),
    'help_btn5': ('bot.funcs.help', 'capasldpalsdallback_main'),
    'help_btn6': ('bot.funcs.help', 'callback_mpaspdoasoain'),
    'help_btn7': ('bot.funcs.help', 'caakodaklspdqlqsqllback_main'),
    'help_btn8': ('bot.funcs.help', 'calakdoaksdaslback_main'),
    'help_btn9': ('bot.funcs.help', 'cadaspdlasaallback_main'),
    'inv_page_': ('bot.funcs.shop', 'process_inventory_pagination'),
    'join_clan': ('bot.handlers.handlers_btns', 'callback_main'),
    'joinorel:': ('bot.funcs.orel', 'join_game_callback'),
    'joinroul_': ('bot.funcs.Roulett', 'Roullet_process_join'),
    'marry1213': ('bot.funcs.top', 'calskqdkqodkqowlback_top'),
    'minejoin:': ('bot.games.mines', 'mines_join_game_callback'),
    'money_won': ('bot.handlers.handlers_btns', 'callback_top'),
    'ob_gpick:': ('bot.funcs.onboarding', 'ob_gpick'),
    'ob_quest:': ('bot.funcs.onboarding', 'ob_quest'),
    'profback:': ('bot.funcs.profile', 'profile_back_callback'),
    'profwarn:': ('bot.funcs.profile', 'profile_warns_callback'),
    'qst:skip:': ('main', 'qst_sub_skip'),
    'reset_row': ('bot.handlers.editprofile', 'reset_row_handler'),
    'rollorel:': ('bot.funcs.orel', 'roll_callback'),
    'rps_join:': ('bot.design.inlinekn', 'inline_knb_join_game_callback'),
    'sell_car_': ('bot.funcs.shopvir', 'sell_car_callback'),
    'shastart:': ('bot.games.scah', 'scah_start_game_callback'),
    'start_btn': ('bot.games.crash', 'accept'),
    'startknb:': ('bot.funcs.knb', 'knb_start_game_callback'),
    'topinvite': ('bot.funcs.top', 'caasqscwqscqllback_top'),
    'view_car_': ('bot.funcs.shopvir', 'view_car'),
    'ach_rev:': ('main', 'achievements_callbacks'),
    'back_btn': ('bot.handlers.handlers_btns', 'callback_main'),
    'balance:': ('bot.funcs.balance', 'cb_balance_refresh'),
    'buy_car_': ('bot.funcs.shopvir', 'process_callback'),
    'cutessss': ('bot.funcs.top', 'callbrgtrgegrewrack_top'),
    'decline_': ('bot.funcs.shop', 'process_decline_callback'),
    'gamehelp': ('bot.funcs.help', 'callbacqwdjqsoqkqzxcvk_top'),
    'gbl_pay:': ('bot.handlers.chatbalance', 'gbl_pay_handler'),
    'joinknb:': ('bot.funcs.knb', 'knb_join_game_callback'),
    'ob_earn:': ('bot.funcs.onboarding', 'ob_earn_page'),
    'ob_game:': ('bot.funcs.onboarding', 'ob_game'),
    'ob_play:': ('bot.funcs.onboarding', 'ob_play'),
    'ob_take:': ('bot.funcs.onboarding', 'ob_take'),
    'setclan:': ('bot.buisnesses.clan_filter', 'process_settings'),
    'shajoin:': ('bot.games.scah', 'scah_join_game_callback'),
    'shamode:': ('bot.games.scah', 'select_mode_callback'),
    'state123': ('bot.funcs.top', 'cb_stats_today'),
    'accept_': ('bot.funcs.shop', 'process_accept_callback'),
    'backtop': ('bot.funcs.top', 'sasadqqwdqwcallback_top'),
    'bostop_': ('bot.games.bombs', 'bombs_stop_game'),
    'button_': ('bot.games.game', 'process_adm_menu'),
    'cancel_': ('bot.funcs.shop', 'cancel_send_item'),
    'crypto_': ('main', 'crypto_choice_handler'),
    'delete_': ('bot.buisnesses.clan_filter', 'process_delete_clan'),
    'marryxp': ('bot.funcs.top', 'callqjiqwjdiqjqback_top'),
    'number_': ('bot.funcs.BlackGack', 'number_callback'),
    'retreat': ('bot.buisnesses.clan_filter', 'handle_retreat'),
    'select:': ('bot.games.scah', 'scah_select_piece_callback'),
    'skipcb:': ('main', 'gift_send_request'),
    'sts:gr:': ('main', 'gift_send_request'),
    'sts:ps:': ('main', 'send_request_callback'),
    'wdwait:': ('main', 'withdraw_wait_buttons_callback'),
    'whoref:': ('bot.funcs.profile', 'profile_refresh_callback'),
    'attack': ('bot.buisnesses.clan_filter', 'handle_attack'),
    'check_': ('bot.funcs.garden', 'handle_check'),
    'empty_': ('bot.games.balls', 'process_callback_ball'),
    'im3412': ('bot.funcs.profile', 'send_im'),
    'kingm:': ('main', 'king_stats_menu_callback'),
    'ktktop': ('bot.funcs.top', 'callbaasdqsdqwcqck_top'),
    'micha:': ('bot.games.scah', 'scah_draw_callback'),
    'staff:': ('bot.admins.mute', 'staff_perms_callback'),
    'sts:g:': ('main', 'btnstars_callback'),
    'topic:': ('server.support_bot', 'cb_topic'),
    'wdact:': ('main', 'admin_withdraw_action_handler'),
    'achm_': ('main', 'achievements_callbacks'),
    'ball_': ('bot.games.balls', 'process_callback_ball'),
    'bomb_': ('bot.games.bombs', 'bombs_process_bomb_click'),
    'ffunc': ('bot.funcs.help', 'caakdoakscijllback_top'),
    'ggsr:': ('main', 'send_request_callback_friend'),
    'greq:': ('main', 'gift_send_request'),
    'page_': ('bot.funcs.shop', 'paginate_handler'),
    'prep:': ('main', 'send_request_callback'),
    '1ref': ('bot.handlers.handlers_btns', 'process_callback_kb1btn1'),
    'brak': ('bot.funcs.help', 'akdfadfkoasdmccallback_top'),
    'dig_': ('bot.funcs.garden', 'process_callback_dig'),
    'pop_': ('bot.games.balls', 'process_callback_ball'),
    'ref1': ('bot.handlers.handlers_btns', 'process_callback_kb1btn1'),
    'spd:': ('main', 'speedconc_request_callback'),
    'srq:': ('main', 'send_request_callback_self'),
    'vip1': ('bot.funcs.profile', 'callback_main'),
    'gc:': ('bot.funcs.balance', 'gc_info_callback'),
}

# exact callback_data -> (module, handler): 173
EXACT_HANDLERS: Dict[str, Tuple[str, str]] = {
    '1st6': ('bot.funcs.BlackGack', 'range_callback'),
    '1to9': ('bot.funcs.BlackGack', 'range_callback'),
    '2nd6': ('bot.funcs.BlackGack', 'range_callback'),
    '3flagcancel_flag_removal': ('bot.funcs.balance', 'cancel_flag_removal'),
    '3rd6': ('bot.funcs.BlackGack', 'range_callback'),
    '9to18': ('bot.funcs.BlackGack', 'range_callback'),
    'EVEN': ('bot.funcs.BlackGack', 'range_callback'),
    'ODD': ('bot.funcs.BlackGack', 'range_callback'),
    'about_start': ('main', 'close_bonus_callback'),
    'accept': ('bot.funcs.marriage', 'process_callback_button_accept'),
    'accept2': ('bot.funcs.marriage', 'process_callback_button_accept'),
    'back': ('server.support_bot', 'cb_back'),
    'back_to_balance': ('bot.handlers.chatbalance', 'back_to_balance'),
    'back_to_stars_choice': ('main', 'back_to_stars_choice'),
    'balanceashudjwqkdq': ('main', '_send_or_edit_wait_notice'),
    'ball_end_stub': ('bot.games.balls', 'ball_end_stub'),
    'ball_paid_stub': ('bot.games.balls', 'ball_paid_stub'),
    'bio_help': ('main', 'bio_help_cb'),
    'black': ('bot.funcs.BlackGack', 'range_callback'),
    'blackmarket_info': ('main', 'blackmarket_info_handler'),
    'blackshop': ('main', 'blackshop_main'),
    'blackshop_balance_info': ('main', 'blackshop_balance_info'),
    'blackshop_my_info': ('main', 'blackshop_my_info'),
    'blackshop_what_is': ('main', 'blackshop_what_is'),
    'bobnusdnusf': ('main', 'bobnusdnusf_cb'),
    'buy341234123412': ('bot.funcs.shop', 'process_buy_callback'),
    'callbroulletanswerhome': ('bot.games.Fortuna', 'fortuna_home_info'),
    'cancel': ('bot.funcs.marriage', 'process_callback_button_cancel'),
    'cancel341234123412': ('bot.funcs.shop', 'process_cancel_callback'),
    'cancel_buy': ('bot.funcs.shopvir', 'cancel_buy_callback'),
    'cancel_clan_creation': ('bot.buisnesses.clan_filter', 'handle_clan_creation_callback'),
    'cancel_delete': ('bot.buisnesses.clan_filter', 'process_cancel_delete'),
    'cancel_gelicopter': ('bot.funcs.Gelicopter', 'cancel_buy_callback'),
    'cancel_gelicoptersell': ('bot.funcs.Gelicopter', 'cancel_sell_callback'),
    'cancel_house': ('bot.funcs.shophouse', 'cancel_buy_callback'),
    'cancel_rename': ('bot.buisnesses.clan_filter', 'process_cancel_rename'),
    'cancel_sell': ('bot.funcs.CuteCoin', 'cancel_sell'),
    'cancelcancel_divorce': ('bot.funcs.marriage', 'cancel_divorce'),
    'canceldell': ('bot.funcs.shop', 'cancel_action'),
    'cancelhouse_sell': ('bot.funcs.shophouse', 'cancel_sell_callback'),
    'cancelsell': ('bot.funcs.shop', 'process_cancel_callback'),
    'cb_gc_abort_finish': ('bot.funcs.balance', 'cb_gc_abort_finish_handler'),
    'cb_gc_abort_menu': ('bot.funcs.balance', 'cb_gc_abort_menu_handler'),
    'check_x2_again': ('main', 'retry_x2_check'),
    'clan_close_message': ('bot.buisnesses.clan_filter', 'process_buy_callback'),
    'clan_list_close': ('bot.buisnesses.clan_filter', 'close_clan_list'),
    'close': ('server.support_bot', 'cb_close'),
    'close1': ('bot.funcs.shophouse', 'process_close_callback'),
    'close12': ('bot.funcs.Gelicopter', 'process_close_callback'),
    'close123123': ('bot.funcs.Gelicopter', 'process_close_callback'),
    'close3412341234123412': ('bot.funcs.shophouse', 'process_close_callback'),
    'close_bonus': ('main', 'close_bonus_callback'),
    'close_freebonus': ('bot.handlers.useitems', 'close_bonus_callback'),
    'close_inventory': ('bot.funcs.shop', 'close_inventory'),
    'close_message_inventory': ('bot.funcs.shop', 'process_buy_callback'),
    'close_shine': ('bot.funcs.Shine', 'close_bonus_callback'),
    'closebonusdfsdfwe': ('main', 'close_bonus_callback'),
    'conc_stars': ('main', 'is_animated_emoji'),
    'craft_cancel': ('bot.funcs.shop', 'craft_cancel_handler'),
    'create': ('server.support_bot', 'cb_create'),
    'daynoop123': ('bot.funcs.top', 'cb_stats_day_noop'),
    'deletehistorygameshistory': ('bot.funcs.history', 'process_buy_callback'),
    'deletehistorygameshistory1': ('bot.funcs.history', 'process_buy_callback'),
    'deletehistorymoneybuttons': ('bot.funcs.history', 'process_buy_callback'),
    'deletehistorymoneybuttons1': ('bot.funcs.history', 'process_buy_callback'),
    'donesub': ('main', 'sub_channel_done'),
    'fullstate123': ('bot.funcs.top', 'cb_stats_all'),
    'gbl_raise': ('bot.handlers.chatbalance', 'gbl_raise_handler'),
    'gc_diff_types': ('main', 'gc_diff_types'),
    'gc_regular_info': ('main', 'gc_regular_info'),
    'group_balance_overview': ('bot.handlers.chatbalance', 'group_balance_overview'),
    'grow_cultures': ('bot.funcs.garden', 'handle_grow_cultures3412'),
    'grow_cultures1': ('bot.funcs.garden', 'handle_grow_cultures1'),
    'help_clans': ('bot.design.inlinetictactoe', 'callback_main'),
    'help_earnings': ('bot.design.inlinetictactoe', 'callback_main'),
    'help_functions': ('bot.design.inlinetictactoe', 'callback_main'),
    'help_games': ('bot.design.inlinetictactoe', 'callback_main'),
    'help_hide': ('bot.design.inlinetictactoe', 'callback_main'),
    'help_info_main': ('bot.design.inlinetictactoe', 'callback_main'),
    'help_market': ('bot.design.inlinetictactoe', 'callback_main'),
    'help_marriages': ('bot.design.inlinetictactoe', 'callback_main'),
    'help_misc': ('bot.design.inlinetictactoe', 'callback_main'),
    'help_profileedit': ('bot.design.inlinetictactoe', 'callback_main'),
    'info_x2': ('main', 'info_x2_cb'),
    'insert_stars': ('main', 'insert_stars_handler'),
    'insert_stars2': ('main', 'insert_stars2_handler'),
    'instantwithdrawal': ('main', 'close_bonus_callback'),
    'minesbetchechtextanswer': ('bot.design.inmine', 'mineahsjidfokadsns_mine_click_callback'),
    'money_won': ('bot.tggames.basket', 'basket_info_stub'),
    'monthnoop123': ('bot.funcs.top', 'cb_stats_month_noop'),
    'my_buyback_info': ('main', 'my_buyback_info_handler'),
    'noop': ('main', 'noop_callback'),
    'noop_gc_empty': ('main', 'gc_noop_empty'),
    'noop_inline_ttt': ('bot.design.inlinetictac2', 'noop_inline_ttt_callback'),
    'noop_ttt': ('bot.funcs.tic_tac_toe', 'noop_ttt_callback'),
    'ob_bonus': ('bot.funcs.onboarding', 'ob_bonus'),
    'ob_earn': ('bot.funcs.onboarding', 'ob_earn'),
    'ob_finish': ('bot.funcs.onboarding', 'ob_finish'),
    'ob_finish_no': ('bot.funcs.onboarding', 'ob_finish_no'),
    'ob_finish_yes': ('bot.funcs.onboarding', 'ob_finish_yes'),
    'ob_games': ('bot.funcs.onboarding', 'ob_games'),
    'ob_menu': ('bot.funcs.onboarding', 'ob_menu'),
    'ob_next': ('bot.funcs.onboarding', 'ob_next'),
    'ob_noop': ('bot.funcs.onboarding', 'ob_noop'),
    'ob_start': ('bot.funcs.onboarding', 'ob_start'),
    'open_base_bonus': ('main', 'open_base_bonus_cb'),
    'open_x2_bonus': ('main', 'open_x2_bonus_cb'),
    'page_info': ('bot.funcs.shop', 'page_info_handler'),
    'plant_apple': ('bot.funcs.garden', 'handle_plant_cabbage'),
    'plant_banana': ('bot.funcs.garden', 'handle_plant_cabbage'),
    'plant_berry': ('bot.funcs.garden', 'handle_plant_corn'),
    'plant_cabbage': ('bot.funcs.garden', 'handle_plant_cabbage'),
    'plant_carrot': ('bot.funcs.garden', 'handle_plant_carrot'),
    'plant_corn': ('bot.funcs.garden', 'handle_plant_corn'),
    'plant_cucumbers': ('bot.funcs.garden', 'handle_plant_cucumbers'),
    'plant_marix': ('bot.funcs.garden', 'handle_plant_marix'),
    'plant_melon': ('bot.funcs.garden', 'handle_plant_cabbage'),
    'plant_potato': ('bot.funcs.garden', 'handle_plant_potato'),
    'plant_tomatoes': ('bot.funcs.garden', 'handle_plant_tomatoes'),
    'popdonateactive': ('bot.funcs.balance', '_build_gc_buttons'),
    'premium_help': ('main', 'premium_help_cb'),
    'proceedproceed_divorce': ('bot.funcs.marriage', 'proceed_divorce'),
    'promo_cancel123xyz': ('bot.funcs.promo', 'cancel_promo'),
    'qst:bal_info': ('main', '_callback_bal_info'),
    'qst:gc_abort_confirm': ('main', 'gc_abort_confirm_callback'),
    'qst:gc_abort_do': ('main', 'gc_abort_do_callback'),
    'qst:gc_abort_do_bal': ('main', 'gc_abort_do_from_balance_callback'),
    'qst:gc_bal_help': ('main', 'gc_bal_help_callback'),
    'qst:gc_help': ('main', 'gc_help_callback'),
    'qst:gc_my': ('main', 'gc_my_assignment_callback'),
    'qst:gc_refresh': ('main', 'gc_refresh_callback'),
    'qst:gc_show_other': ('main', 'gc_show_other'),
    'qst:menu_back': ('main', 'qst_menu_back'),
    'qst:show_gc': ('main', 'gc_show_menu'),
    'qst:show_subs': ('main', 'qst_show_subs'),
    'qst:show_subs_normal': ('main', 'qst_show_subs_normal'),
    'qst:sub_refresh': ('main', 'qst_sub_refresh'),
    'qst:withdraw_ok': ('main', 'qst_withdraw_ok'),
    'questions_stars': ('main', 'questions_stars_menu'),
    'red': ('bot.funcs.BlackGack', 'range_callback'),
    'reject': ('bot.funcs.marriage', 'process_callback_button_reject'),
    'reject2': ('bot.funcs.marriage', 'process_callback_button_reject'),
    'reset_sorting': ('bot.funcs.shop', 'reset_filter_handler'),
    'return_to_buy_menu': ('bot.funcs.shophouse', 'return_to_buy_cars'),
    'return_to_gelicopter1231_menu': ('bot.funcs.Gelicopter', 'return_to_sell_menu'),
    'return_to_gelicopter_menu': ('bot.funcs.Gelicopter', 'return_to_buy_gelicopter'),
    'return_to_my_cars': ('bot.funcs.shopvir', 'return_to_my_cars'),
    'return_to_my_gelicopter': ('bot.funcs.Gelicopter', 'return_to_my_gelicopter'),
    'return_to_my_house': ('bot.funcs.shophouse', 'return_to_my_house'),
    'return_to_sell_menu': ('bot.funcs.shopvir', 'return_to_sell_menu'),
    'return_to_sellhouse_menu': ('bot.funcs.shophouse', 'return_to_sell_menu'),
    'risk_end_stub': ('bot.games.risk', 'risk_end_stub'),
    'sellitem': ('bot.funcs.shop', 'process_sell_callback'),
    'shineshine': ('bot.funcs.Shine', 'process_callback'),
    'shoot_bot': ('bot.games.bullet', 'game_actions'),
    'shoot_self': ('bot.games.bullet', 'game_actions'),
    'show_balance': ('bot.design.inlinekn', 'show_balance_handler'),
    'show_cute_amount': ('main', 'show_cute_amount_callback'),
    'show_date': ('main', 'show_date_callback'),
    'show_username': ('main', 'show_username_callback'),
    'spin': ('bot.games.bullet', 'game_actions'),
    'status': ('server.support_bot', 'cb_status'),
    'store_close_message': ('bot.funcs.shop', 'process_close_store'),
    'store_craft_close_message': ('bot.handlers.useitems', 'close_message'),
    'subcutechat3': ('main', 'close_bonus_callback'),
    'tech_works_info': ('main', 'tech_works_info'),
    'weeknoop123': ('bot.funcs.top', 'cb_stats_week_noop'),
    'winnerminesanswertext': ('bot.design.inmine', 'mines_mineasdufioiaasd_click_callback'),
    'wordcancel_game': ('bot.games.word', 'cancel_game'),
    'wordswin_congrats': ('main', 'wordswin_congrats'),
    'wordswin_ok': ('main', 'wordswin_ok'),
    'wwwithdrawsss': ('bot.funcs.balance', '_build_gc_buttons'),
    'yearnoop123': ('bot.funcs.top', 'cb_stats_year_noop'),
}

def all_known_prefixes() -> List[str]:
    return sorted(PREFIX_HANDLERS.keys(), key=len, reverse=True)

